name: Tests
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v ./cmd/glab

  build-minimum:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./cmd/glab
      
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./cmd/glab
        
      - name: Add GOPATH/bin to PATH
        run: echo "::add-path::$(go env GOPATH)/bin"
    
      - name: Run tests
        run: | 
          export GOPATH=$(go env GOPATH)
          sudo make tests
      - name: Upload Unit Test Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
